var states = {
"AGUASCALIENTES" : "mx-ag",
"BAJA CALIFORNIA": "mx-bc",
"BAJA CALIFORNIA SUR" : "mx-bs",
"CAMPECHE" : "mx-cm",
"CHIAPAS" : "mx-cs",
"CHIHUAHUA" : "mx-ch",
"COAHUILA DE ZARAGOZA" : "mx-co",
"COLIMA" : "mx-cl",
"DISTRITO FEDERAL" : "mx-df",
"DURANGO" : "mx-dg",
"ESTADO DE MEXICO" : "mx-mx",
"GUANAJUATO" : "mx-gj",
"GUERRERO" : "mx-gr",
"HIDALGO" : "mx-hg",
"JALISCO" : "mx-ja",
"MICHOACAN DE OCAMPO" : "mx-mi",
"MORELOS" : "mx-mo",
"NAYARIT" : "mx-na",
"NUEVO LEON" : "mx-nl",
"OAXACA" : "mx-oa",
"PUEBLA" : "mx-pu",
"QUERETARO" : "mx-qt",
"QUINTANA ROO" : "mx-qr",
"SAN LUIS POTOSI" : "mx-sl",
"SINALOA" : "mx-si",
"SONORA" : "mx-so",
"TABASCO" : "mx-tb",
"TAMAULIPAS" : "mx-tm",
"TLAXCALA" : "mx-tl",
"VERACRUZ DE IGNACIO DE LA LLAVE" : "mx-ve",
"YUCATAN" : "mx-yu",
"ZACATECAS" : "mx-za"
};
